name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to access IAM Role with OIDC
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: 761633760558.dkr.ecr.us-west-2.amazonaws.com/eks-helm-deploy
          tags: |
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=pr,suffix=-{{sha}}
            type=ref,event=tag

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::761633760558:role/RaydiantGithubActionsEcr-production
          role-session-name: github-actions-eks-helm-deploy-build
          aws-region: us-west-2

      - name: Login to Amazon ECR
        #if: ${{ github.event_name != 'pull_request' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          #push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
